export const TEAM_MEMBERS = {
  "Team 7": [
    "shohidulbari",
    "MusavvirK",
    "refkarim",
    "yasinarefin",
    "Mehedi-Hassan",
    "Aryan3212",
  ],
  "API Team": [
    "dustyRAIN",
    "shunjid",
    "AhsanShihab",
    "farzeen-naz",
    "atiq1589",
    "frrahat",
  ],
  "Team 4": [
    "debasisroy144",
    "ahmedsadman",
    "rhs99",
    "zahinahmed12",
    "sgtlaugh",
    "ahmed-dinar",
    "farhanfuad35",
  ],
  "Team 8": ["jjmalina", "sajedul-karim", "mumin91", "imran2140"],
  "Team Skynet": [
    "ashiqursuperfly",
    "pratikjoy7",
    "reshadmrrr",
    "SakibAbrar",
    "amardebnath",
    "mredulorfiaz",
    "rizwan192",
    "hsiam261",
  ],
  "Team Axiom": ["radnan", "MunifTanjim", "JafarSaifullah", "toha993"],
  "Platform Team": [
    "DiptoBarua918",
    "radnan",
    "MunifTanjim",
    "Anjum219",
    "kfoozminus",
    "mauricecruz",
    "syednabilashraf",
    "tajrian",
    "gaspardip",
    "tanvirstreame",
  ],
  "Team 1": [
    "mostafa-K-raihan",
    "kmtusher97",
    "kamrul1157024",
    "raykibul",
    "zhdzmn",
  ],
  "Team 8": ["imran2140", "jjmalina", "mumin91", "sajedul-karim"],
};
